Quickstart
==========

In this short tutorial we will guide you through a series of steps that
will help you getting started using **SDV**.

Model the dataset using SDV
---------------------------

To model a multi table, relational dataset, we follow two steps. In the
first step, we will load the data and configures the meta data. In the
second step, we will use the SDV API to fit and save a hierarchical
model. We will cover these two steps in this section using an example
dataset.

### Load example data

**SDV** comes with a toy dataset to play with, which can be loaded using
the `sdv.load_demo` function:

In [1]:
from sdv import load_demo

metadata, tables = load_demo(metadata=True)

This will return two objects:

1.  A `Metadata` object with all the information that **SDV** needs to
    know about the dataset.

In [2]:
metadata

Metadata
  root_path: .
  tables: ['users', 'sessions', 'transactions']
  relationships:
    sessions.user_id -> users.user_id
    transactions.session_id -> sessions.session_id

In [3]:
metadata.visualize()

For more details about how to build the `Metadata` for your own dataset,
please refer to the [Relational Metadata](relational_data/01_Relational_Metadata.ipynb)
guide.

2.  A dictionary containing three `pandas.DataFrames` with the tables
    described in the metadata object.

In [4]:
tables

{'users':    user_id country gender  age
 0        0      US      M   34
 1        1      UK      F   23
 2        2      ES   None   44
 3        3      UK      M   22
 4        4      US      F   54
 5        5      DE      M   57
 6        6      BG      F   45
 7        7      ES   None   41
 8        8      FR      F   23
 9        9      UK   None   30,
 'sessions':    session_id  user_id  device       os  minutes
 0           0        0  mobile  android       23
 1           1        1  tablet      ios       12
 2           2        1  tablet  android        8
 3           3        2  mobile  android       13
 4           4        4  mobile      ios        9
 5           5        5  mobile  android       32
 6           6        6  mobile      ios        7
 7           7        6  tablet      ios       21
 8           8        6  mobile      ios       29
 9           9        8  tablet      ios       34,
 'transactions':    transaction_id  session_id           timestamp  amount  cancelled
 0               0           0 2019-01-01 12:34:32   100.0      False
 1               1           0 2019-01-01 12:42:21    55.3      False
 2               2           1 2019-01-07 17:23:11    79.5      False
 3               3           3 2019-01-10 11:08:57   112.1       True
 4               4           5 2019-01-10 21:54:08   110.0       True
 5               5           5 2019-01-11 11:21:20    76.3      False
 6               6           7 2019-01-22 14:44:10    89.5      False
 7               7           8 2019-01-23 10:14:09   132.1       True
 8               8           9 2019-01-27 16:09:17    68.0      False
 9               9           9 2019-01-29 12:10:48    99.9      False}

### Fit a model using the SDV API.

First, we build a hierarchical statistical model of the data using
**SDV**. For this we will create an instance of the `sdv.SDV` class and
use its `fit` method.

During this process, **SDV** will traverse across all the tables in your
dataset following the primary key-foreign key relationships and learn
the probability distributions of the values in the columns.

In [5]:
from sdv import SDV

sdv = SDV()
sdv.fit(metadata, tables)

Sample data from the fitted model
---------------------------------

Once the modeling has finished you are ready to generate new synthetic
data using the `sdv` instance that you have.

For this, all you have to do is call the `sample_all` method from your
instance passing the number of rows that you want to generate:

In [6]:
sampled = sdv.sample_all()

This will return a dictionary identical to the `tables` one that we
passed to the SDV instance for learning, filled in with new synthetic
data.

<div class="alert alert-info">

**Note**

Only the parent tables of your dataset will have the specified number of
rows, as the number of child rows that each row in the parent table has
is also sampled following the original distribution of your dataset.

</div>

In [7]:
sampled

{'users':    user_id country gender  age
 0        0      ES    NaN   47
 1        1      US    NaN   30
 2        2      UK    NaN   59
 3        3      ES    NaN   35
 4        4      FR    NaN   40
 5        5      UK    NaN   44
 6        6      UK      F   31
 7        7      US      F   46
 8        8      UK      M   28
 9        9      ES      F   40,
 'sessions':    session_id  user_id  device       os  minutes
 0           0        0  mobile  android       19
 1           1        2  mobile  android       32
 2           2        2  mobile  android       38
 3           3        3  tablet      ios       23
 4           4        7  mobile  android       18
 5           5        7  mobile      ios       15
 6           6        8  tablet      ios       20
 7           7        9  tablet      ios       12,
 'transactions':    transaction_id  session_id           timestamp      amount  cancelled
 0               0           0 2019-01-08 02:07:18   79.153908      False
 1               1           1 2019-01-11 19:52:35   98.033938      False
 2               2           1 2019-01-12 02:13:17  103.260843      False
 3               3           2 2019-01-13 06:11:08   88.578722       True
 4               4           2 2019-01-13 07:38:11   90.354901       True
 5               5           3 2019-01-28 18:27:01  103.260802      False
 6               6           4 2019-01-16 09:49:22  112.102569      False
 7               7           6 2019-01-12 05:20:44  100.850073      False
 8               8           7 2019-01-21 03:46:39   29.372589      False}

Saving and Loading your model
-----------------------------

In some cases, you might want to save the fitted SDV instance to be able
to generate synthetic data from it later or on a different system.

In order to do so, you can save your fitted `SDV` instance for later
usage using the `save` method of your instance.

In [8]:
sdv.save('sdv.pkl')

The generated `pkl` file will not include any of the original data in
it, so it can be safely sent to where the synthetic data will be
generated without any privacy concerns.

Later on, in order to sample data from the fitted model, we will first
need to load it from its `pkl` file.

In [9]:
sdv = SDV.load('sdv.pkl')

After loading the instance, we can sample synthetic data using its
`sample_all` method like before.

In [10]:
sampled = sdv.sample_all(5)
sampled

{'users':    user_id country gender  age
 0       10      ES    NaN   35
 1       11      UK    NaN   23
 2       12      FR      F   47
 3       13      US    NaN   41
 4       14      US      F   25,
 'sessions':    session_id  user_id  device       os  minutes
 0           8       10  tablet      ios       39
 1           9       12  mobile      ios        9
 2          10       12  mobile      ios       15
 3          11       12  mobile      ios       17
 4          12       13  tablet      ios        3
 5          13       13  tablet      ios        4
 6          14       13  mobile      ios       -1
 7          15       14  mobile  android       25,
 'transactions':    transaction_id  session_id           timestamp     amount  cancelled
 0               9           8 2019-01-22 18:11:12  73.944190       True
 1              10           8 2019-01-22 19:25:00  95.516283      False
 2              11          15 2019-01-05 23:31:17  42.438428      False
 3              12          15 2019-01-05 08:19:26  90.406043      False}